/*
* This header is generated by classdump-dyld 1.0
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/rapportd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol NSXPCListenerDelegate <NSObject>
@optional
-(char)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;

@end

