/*
* This header is generated by classdump-dyld 1.0
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/rapportd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct {
	double lastLogTime;
	unsigned long long bytesAdded;
	unsigned long long messagesAdded;
} SCD_Struct_RP0;

typedef struct __IOHIDEventSystemClient* IOHIDEventSystemClientRef;

typedef struct __IOHIDUserDevice* IOHIDUserDeviceRef;

