/*
* This header is generated by classdump-dyld 1.0
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/rapportd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDictionary, RPCloudMessageContext;

@interface RPBufferedCloudMessage : NSObject {

	unsigned char _frameType;
	NSDictionary* _message;
	RPCloudMessageContext* _msgCtx;

}

@property (assign,nonatomic) unsigned char frameType;                     //@synthesize frameType=_frameType - In the implementation block
@property (nonatomic,copy) NSDictionary * message;                        //@synthesize message=_message - In the implementation block
@property (nonatomic,retain) RPCloudMessageContext * msgCtx;              //@synthesize msgCtx=_msgCtx - In the implementation block
-(NSDictionary *)message;
-(void)setMessage:(NSDictionary *)arg1 ;
-(void)setFrameType:(unsigned char)arg1 ;
-(unsigned char)frameType;
-(RPCloudMessageContext *)msgCtx;
-(void)setMsgCtx:(RPCloudMessageContext *)arg1 ;
@end

