/*
* This header is generated by classdump-dyld 1.0
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/rapportd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface RPCloudMessageContext : NSObject {

	NSString* _appleID;
	NSString* _cloudServiceID;
	NSString* _fromID;
	NSString* _sendersKnownAlias;
	NSString* _toID;

}

@property (nonatomic,retain) NSString * appleID;                        //@synthesize appleID=_appleID - In the implementation block
@property (nonatomic,retain) NSString * cloudServiceID;                 //@synthesize cloudServiceID=_cloudServiceID - In the implementation block
@property (nonatomic,retain) NSString * fromID;                         //@synthesize fromID=_fromID - In the implementation block
@property (nonatomic,retain) NSString * sendersKnownAlias;              //@synthesize sendersKnownAlias=_sendersKnownAlias - In the implementation block
@property (nonatomic,retain) NSString * toID;                           //@synthesize toID=_toID - In the implementation block
-(NSString *)sendersKnownAlias;
-(void)setSendersKnownAlias:(NSString *)arg1 ;
-(NSString *)appleID;
-(void)setAppleID:(NSString *)arg1 ;
-(void)setFromID:(NSString *)arg1 ;
-(NSString *)fromID;
-(void)setToID:(NSString *)arg1 ;
-(NSString *)toID;
-(NSString *)cloudServiceID;
-(void)setCloudServiceID:(NSString *)arg1 ;
@end

