/*
* This header is generated by classdump-dyld 1.0
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/rapportd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSObject, HMHomeManager, NSArray;

@interface RPHomeKitManager : NSObject {

	char _invalidateCalled;
	/*^block*/id _mediaGroupsChangedHandler;
	NSObject*<OS_dispatch_queue> _dispatchQueue;
	HMHomeManager* _homeManager;
	NSArray* _homeKitCurrentUserIDs;

}

@property (nonatomic,retain) HMHomeManager * homeManager;                             //@synthesize homeManager=_homeManager - In the implementation block
@property (nonatomic,retain) NSArray * homeKitCurrentUserIDs;                         //@synthesize homeKitCurrentUserIDs=_homeKitCurrentUserIDs - In the implementation block
@property (assign,nonatomic) char invalidateCalled;                                   //@synthesize invalidateCalled=_invalidateCalled - In the implementation block
@property (nonatomic,copy) id mediaGroupsChangedHandler;                              //@synthesize mediaGroupsChangedHandler=_mediaGroupsChangedHandler - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> dispatchQueue;              //@synthesize dispatchQueue=_dispatchQueue - In the implementation block
-(void)invalidate;
-(NSObject*<OS_dispatch_queue>)dispatchQueue;
-(id)initWithQueue:(id)arg1 ;
-(void)setDispatchQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(id)homeKitUserIdentifiers;
-(HMHomeManager *)homeManager;
-(void)setHomeManager:(HMHomeManager *)arg1 ;
-(char)invalidateCalled;
-(void)setInvalidateCalled:(char)arg1 ;
-(id)filterHomeKitUserIdentifiers:(id)arg1 ;
-(void)resetHomeKitUserIdentifiers;
-(id)mediaGroupsChangedHandler;
-(void)setMediaGroupsChangedHandler:(id)arg1 ;
-(NSArray *)homeKitCurrentUserIDs;
-(void)setHomeKitCurrentUserIDs:(NSArray *)arg1 ;
@end

