/*
* This header is generated by classdump-dyld 1.0
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/rapportd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/RPSubDaemonable.h>

@protocol OS_dispatch_queue;
@class CUCoalescer, NSArray, RPIdentity, NSMutableArray, CUSystemMonitor, NSObject, NSString;

@interface RPIdentityDaemon : NSObject <RPSubDaemonable> {

	int _homeViewChangeToken;
	CUCoalescer* _identitiesChangedCoalescer;
	char _invalidateCalled;
	char _invalidateDone;
	unsigned long long _keychainRefetchTicks;
	NSArray* _pairedDeviceIdentities;
	int _pairedDevicesNotifier;
	char _prefFamilyResolve;
	char _prefFriendResolve;
	char _prefOwnerResolve;
	char _prefPairedResolve;
	char _prefSharedHomeResolve;
	NSArray* _sameAccountDeviceIdentities;
	RPIdentity* _selfIdentityCache;
	NSMutableArray* _sharedHomeDeviceIdentities;
	NSMutableArray* _sharedHomeExtraDeviceIdentities;
	CUSystemMonitor* _systemMonitor;
	NSObject*<OS_dispatch_queue> _dispatchQueue;
	RPIdentity* _homeKitIdentity;

}

@property (nonatomic,retain) RPIdentity * homeKitIdentity;                            //@synthesize homeKitIdentity=_homeKitIdentity - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> dispatchQueue;              //@synthesize dispatchQueue=_dispatchQueue - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedIdentityDaemon;
-(id)init;
-(void)_activate;
-(void)invalidate;
-(void)_invalidate;
-(NSObject*<OS_dispatch_queue>)dispatchQueue;
-(void)_update;
-(void)activate;
-(void)_invalidated;
-(void)setDispatchQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(void)_ensureStarted;
-(void)_ensureStopped;
-(id)descriptionWithLevel:(int)arg1 ;
-(id)identityOfSelfAndReturnError:(id*)arg1 ;
-(id)resolveIdentityForSignature:(id)arg1 data:(id)arg2 typeFlags:(unsigned)arg3 error:(id*)arg4 ;
-(RPIdentity *)homeKitIdentity;
-(unsigned)resolveIdentityTypesForSignature:(id)arg1 data:(id)arg2 typeFlags:(unsigned)arg3 ;
-(char)saveIdentityWithIDSDeviceID:(id)arg1 message:(id)arg2 error:(id*)arg3 ;
-(void)addSharedHomeIdentityWithRPMessage:(id)arg1 ;
-(void)addSelfIdentityInfoToMessage:(id)arg1 flags:(unsigned)arg2 ;
-(char)removeIdentity:(id)arg1 error:(id*)arg2 ;
-(void)prefsChanged;
-(void)daemonInfoChanged:(unsigned long long)arg1 ;
-(char)diagnosticCommand:(id)arg1 params:(id)arg2 ;
-(char)addXPCMatchingToken:(unsigned long long)arg1 event:(id)arg2 handler:(/*^block*/id)arg3 ;
-(char)removeXPCMatchingToken:(unsigned long long)arg1 ;
-(id)resolveIdentityForBonjourDevice:(id)arg1 typeFlags:(unsigned)arg2 ;
-(id)resolveIdentitiesForBonjourDevice:(id)arg1 typeFlags:(unsigned)arg2 ;
-(id)identitiesOfType:(int)arg1 error:(id*)arg2 ;
-(void)resolvableAccessoriesUpdated:(id)arg1 ;
-(void)setHomeKitIdentity:(RPIdentity *)arg1 ;
-(void)_loadSelfIdentity:(char)arg1 ;
-(void)_updateSameAccountIdentities;
-(void)_triggerKeychainRefetch;
-(void)_saveSelfIdentityPrivate:(id)arg1 ;
-(void)_saveSelfIdentityPublicWithPrivateIdentity:(id)arg1 force:(char)arg2 ;
-(void)_postIdentitiesChangedNotification;
-(id)_identitiesOfType:(int)arg1 error:(id*)arg2 ;
-(char)saveIdentity:(id)arg1 error:(id*)arg2 ;
-(void)_updatePairedDeviceIdentities;
-(unsigned)_updateSelfIdentityPrivate:(id)arg1 create:(char)arg2 ;
-(unsigned)_updateSelfIdentityPublic:(id)arg1 privateIdentity:(id)arg2 ;
-(void)regenerateSelfIdentity:(id)arg1 ;
@end

