/*
* This header is generated by classdump-dyld 1.0
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/rapportd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
#import <rapportd/rapportd-Structs.h>
@class NSObject;

@interface RPMetrics : NSObject {

	NSObject*<OS_dispatch_queue> _dispatchQueue;

}

@property (nonatomic,retain) NSObject*<OS_dispatch_queue> dispatchQueue;              //@synthesize dispatchQueue=_dispatchQueue - In the implementation block
+(id)sharedMetrics;
+(id)sharedMetricsNoCreate;
-(id)init;
-(void)_activate;
-(void)invalidate;
-(NSObject*<OS_dispatch_queue>)dispatchQueue;
-(void)activate;
-(void)setDispatchQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(id)descriptionWithLevel:(int)arg1 ;
-(void)logReceivedMessageType:(int)arg1 identifier:(id)arg2 options:(id)arg3 appID:(id)arg4 ctx:(SCD_Struct_RP0*)arg5 ;
-(void)_logReceivedMessageType:(int)arg1 identifier:(id)arg2 options:(id)arg3 appID:(id)arg4 timeBegin:(double)arg5 timeEnd:(double)arg6 bytesAdded:(unsigned long long)arg7 messagesAdded:(unsigned long long)arg8 ;
@end

