/*
* This header is generated by classdump-dyld 1.0
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/rapportd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol RPPrivateDiscoveryXPCDaemonInterface
@required
-(void)xpcPrivateAdvertiserActivate:(id)arg1 completion:(/*^block*/id)arg2;
-(void)xpcPrivateAdvertiserUpdate:(id)arg1 completion:(/*^block*/id)arg2;
-(void)xpcPrivateDiscoveryActivate:(id)arg1 completion:(/*^block*/id)arg2;
-(void)xpcPrivateDiscoveryUpdate:(id)arg1 completion:(/*^block*/id)arg2;

@end

