/*
* This header is generated by classdump-dyld 1.0
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/rapportd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/RPPrivateDiscoveryXPCDaemonInterface.h>

@protocol OS_dispatch_queue;
@class RPPrivateAdvertiser, RPPrivateDiscovery, RPPrivateDaemon, NSObject, NSXPCConnection;

@interface RPPrivateXPCConnection : NSObject <RPPrivateDiscoveryXPCDaemonInterface> {

	char _direct;
	char _entitled;
	RPPrivateAdvertiser* _activatedAdvertiser;
	RPPrivateDiscovery* _activatedDiscovery;
	RPPrivateDaemon* _daemon;
	NSObject*<OS_dispatch_queue> _dispatchQueue;
	NSXPCConnection* _xpcCnx;

}

@property (nonatomic,readonly) RPPrivateAdvertiser * activatedAdvertiser;              //@synthesize activatedAdvertiser=_activatedAdvertiser - In the implementation block
@property (nonatomic,readonly) RPPrivateDiscovery * activatedDiscovery;                //@synthesize activatedDiscovery=_activatedDiscovery - In the implementation block
@property (nonatomic,retain) RPPrivateDaemon * daemon;                                 //@synthesize daemon=_daemon - In the implementation block
@property (assign,nonatomic) char direct;                                              //@synthesize direct=_direct - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> dispatchQueue;               //@synthesize dispatchQueue=_dispatchQueue - In the implementation block
@property (assign,nonatomic) char entitled;                                            //@synthesize entitled=_entitled - In the implementation block
@property (nonatomic,retain) NSXPCConnection * xpcCnx;                                 //@synthesize xpcCnx=_xpcCnx - In the implementation block
-(NSObject*<OS_dispatch_queue>)dispatchQueue;
-(void)setDispatchQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(char)direct;
-(RPPrivateDaemon *)daemon;
-(void)setDirect:(char)arg1 ;
-(NSXPCConnection *)xpcCnx;
-(char)_entitledAndReturnError:(id*)arg1 ;
-(char)entitled;
-(void)setDaemon:(RPPrivateDaemon *)arg1 ;
-(void)setEntitled:(char)arg1 ;
-(void)xpcPrivateAdvertiserActivate:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)xpcPrivateAdvertiserUpdate:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)xpcPrivateDiscoveryActivate:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)xpcPrivateDiscoveryUpdate:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)setXpcCnx:(NSXPCConnection *)arg1 ;
-(void)xpcConnectionInvalidated;
-(RPPrivateDiscovery *)activatedDiscovery;
-(RPPrivateAdvertiser *)activatedAdvertiser;
@end

