/*
* This header is generated by classdump-dyld 1.0
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/rapportd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol RPRemoteDisplayXPCDaemonInterface
@required
-(void)remoteDisplayActivateDiscovery:(id)arg1 completion:(/*^block*/id)arg2;
-(void)remoteDisplayActivateServer:(id)arg1 completion:(/*^block*/id)arg2;
-(void)remoteDisplayActivateSession:(id)arg1 completion:(/*^block*/id)arg2;
-(void)remoteDisplayInvalidateSessionID:(id)arg1;
-(void)remoteDisplayTryPassword:(id)arg1;
-(void)remoteDisplaySendEventID:(id)arg1 event:(id)arg2 options:(id)arg3 completion:(/*^block*/id)arg4;
-(void)remoteDisplaySendRequestID:(id)arg1 request:(id)arg2 options:(id)arg3 responseHandler:(/*^block*/id)arg4;

@end

