/*
* This header is generated by classdump-dyld 1.0
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/rapportd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue, RPMessageable;
@class NSObject, RPSiriAudioSession;

@interface RPSiriDaemon : NSObject {

	NSObject*<OS_dispatch_queue> _dispatchQueue;
	RPSiriAudioSession* _siriAudioSession;
	id<RPMessageable> _messenger;

}

@property (nonatomic,retain) id<RPMessageable> messenger;              //@synthesize messenger=_messenger - In the implementation block
-(id)init;
-(void)invalidate;
-(char)activateAndReturnError:(id*)arg1 ;
-(id<RPMessageable>)messenger;
-(void)setMessenger:(id<RPMessageable>)arg1 ;
-(void)_handleSiriAudio:(id)arg1 ;
-(void)_handleSiriStart:(id)arg1 responseHandler:(/*^block*/id)arg2 ;
-(void)_handleSiriStop:(id)arg1 responseHandler:(/*^block*/id)arg2 ;
@end

