/*
* This header is generated by classdump-dyld 1.0
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/rapportd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDictionary, RPServer;

@interface RPXPCMatchingEntry : NSObject {

	char _appSignIn;
	char _state;
	NSDictionary* _event;
	/*^block*/id _handler;
	RPServer* _server;
	unsigned long long _token;

}

@property (assign,nonatomic) char appSignIn;                        //@synthesize appSignIn=_appSignIn - In the implementation block
@property (nonatomic,copy) NSDictionary * event;                    //@synthesize event=_event - In the implementation block
@property (nonatomic,copy) id handler;                              //@synthesize handler=_handler - In the implementation block
@property (nonatomic,retain) RPServer * server;                     //@synthesize server=_server - In the implementation block
@property (assign,nonatomic) char state;                            //@synthesize state=_state - In the implementation block
@property (assign,nonatomic) unsigned long long token;              //@synthesize token=_token - In the implementation block
-(char)state;
-(void)setServer:(RPServer *)arg1 ;
-(void)setState:(char)arg1 ;
-(id)handler;
-(void)setHandler:(id)arg1 ;
-(NSDictionary *)event;
-(unsigned long long)token;
-(RPServer *)server;
-(void)setToken:(unsigned long long)arg1 ;
-(void)setEvent:(NSDictionary *)arg1 ;
-(void)setAppSignIn:(char)arg1 ;
-(char)appSignIn;
@end

